-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 12:26:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema onemediapiece
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onemediapiece`;
CREATE SCHEMA IF NOT EXISTS `onemediapiece` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CREATE USER `onemediapiece`@`%` IDENTIFIED BY 'azerty-12';
-- CREATE USER `onemediapiece`@`localhost` IDENTIFIED BY 'azerty-12';
-- GRANT ALL PRIVILEGES ON `onemediapiece`.* TO `onemediapiece`@`localhost`;
-- GRANT ALL PRIVILEGES ON `onemediapiece`.* TO `onemediapiece`@`%`;

-- -----------------------------------------------------
-- Schema onemediapiece_test
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `onemediapiece_test`;
-- CREATE SCHEMA IF NOT EXISTS `onemediapiece_test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
-- CREATE USER `onemediapiece_test`@`%` IDENTIFIED BY '_azerty';
-- CREATE USER `onemediapiece_test`@`localhost` IDENTIFIED BY '_azerty';
-- GRANT ALL PRIVILEGES ON `onemediapiece_test`.* TO `onemediapiece_test`@`localhost`;
-- GRANT ALL PRIVILEGES ON `onemediapiece_test`.* TO `onemediapiece_test`@`%`;
